# Generated by Django 4.2.7 on 2023-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.RemoveField(
            model_name='board',
            name='create_date',
        ),
        migrations.AddField(
            model_name='board',
            name='birth',
            field=models.CharField(default='0000-00-00', max_length=100),
        ),
        migrations.AddField(
            model_name='board',
            name='email',
            field=models.CharField(default='example@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='no',
            field=models.CharField(default='0000', max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='tel',
            field=models.CharField(default='000-0000-0000', max_length=200),
        ),
    ]
